services:
  - type: web
    name: pinterest-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m pinterest_scraper.web
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
