services:
  - type: web
    name: pinterest-scraper
    env: python
    buildCommand: pip install -e . && pip install -r requirements.txt
    startCommand: python -m __main__ server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

